# Generated by Django 2.2.5 on 2021-02-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
